"""SAM2 wrapper (CUDA-ready) + classical CPU assist fallback + mask generation.

HONESTY CONTRACT:
- SAM2 heavy inference only runs when a real CUDA GPU + the sam2 package are available.
- On CPU-only environments the `propose` endpoint uses a clearly-labeled classical
  region-growing assist (NOT SAM2). The response always states which backend produced it.
- We never claim a GPU/SAM2 execution happened when it did not.
"""
import io
import json
import numpy as np
from PIL import Image, ImageDraw, ImageOps
import cv2

import config
import storage

# Lazy singleton for the real SAM2 predictor (only built on GPU)
_sam2_predictor = None


def torch_cuda_ready() -> bool:
    try:
        import torch
        return torch.cuda.is_available()
    except Exception:
        return False


def sam2_installed() -> bool:
    try:
        import importlib.util
        return importlib.util.find_spec("sam2") is not None
    except Exception:
        return False


def sam2_status() -> dict:
    cuda = torch_cuda_ready()
    installed = sam2_installed()
    gpu_ready = cuda and installed
    if gpu_ready:
        backend = "sam2_cuda"
        msg = "SAM2 ready on CUDA GPU. Point-prompt proposals use the real SAM2 model."
    elif cuda and not installed:
        backend = "cpu_assist_fallback"
        msg = "CUDA present but sam2 package not installed. Install sam2 to enable GPU proposals."
    else:
        backend = "cpu_assist_fallback"
        msg = ("No CUDA GPU. Point-prompt proposals use a classical CPU region-growing assist "
               "(NOT SAM2). SAM2 requires a GPU and will activate automatically when available.")
    return {
        "sam2_installed": installed,
        "cuda_available": cuda,
        "gpu_ready": gpu_ready,
        "active_backend": backend,
        "message": msg,
    }


def _load_sam2():
    global _sam2_predictor
    if _sam2_predictor is not None:
        return _sam2_predictor
    from sam2.build_sam import build_sam2
    from sam2.sam2_image_predictor import SAM2ImagePredictor
    import torch
    ckpt = config.os.environ.get("SAM2_CHECKPOINT", "/app/models/sam2_hiera_large.pt")
    cfg = config.os.environ.get("SAM2_CONFIG", "sam2_hiera_l.yaml")
    model = build_sam2(cfg, ckpt, device="cuda")
    _sam2_predictor = SAM2ImagePredictor(model)
    return _sam2_predictor


def _mask_to_polygons(mask: np.ndarray, max_points: int = 80):
    contours, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    polygons = []
    for c in sorted(contours, key=cv2.contourArea, reverse=True):
        if cv2.contourArea(c) < 50:
            continue
        peri = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, 0.004 * peri, True)
        pts = [[int(p[0][0]), int(p[0][1])] for p in approx]
        if len(pts) >= 3:
            polygons.append(pts)
    return polygons


def propose(image_bytes: bytes, positive_points, negative_points=None, tolerance: int = 22) -> dict:
    """Return proposed polygon(s) for a plane given point prompts."""
    img = np.array(ImageOps.exif_transpose(Image.open(io.BytesIO(image_bytes))).convert("RGB"))
    h, w = img.shape[:2]
    status = sam2_status()

    if status["gpu_ready"]:
        import torch
        predictor = _load_sam2()
        predictor.set_image(img)
        pts = np.array(positive_points + (negative_points or []), dtype=np.float32)
        labels = np.array([1] * len(positive_points) + [0] * len(negative_points or []), dtype=np.int32)
        with torch.inference_mode():
            masks, scores, _ = predictor.predict(point_coords=pts, point_labels=labels, multimask_output=True)
        best = masks[int(np.argmax(scores))].astype(np.uint8) * 255
        polygons = _mask_to_polygons(best)
        return {"backend": "sam2_cuda", "polygons": polygons,
                "note": "Proposal generated by SAM2 on CUDA GPU."}

    # ---- CPU classical assist (NOT SAM2) ----
    seed = positive_points[0]
    seed = (int(np.clip(seed[0], 0, w - 1)), int(np.clip(seed[1], 0, h - 1)))
    flood_mask = np.zeros((h + 2, w + 2), np.uint8)
    flags = 4 | cv2.FLOODFILL_MASK_ONLY | (255 << 8)
    cv2.floodFill(img.copy(), flood_mask, seed, 0,
                  (tolerance,) * 3, (tolerance,) * 3, flags)
    m = flood_mask[1:-1, 1:-1]
    m = cv2.morphologyEx(m, cv2.MORPH_CLOSE, np.ones((5, 5), np.uint8))
    polygons = _mask_to_polygons(m)
    return {"backend": "cpu_assist_fallback", "polygons": polygons,
            "note": "CPU region-growing assist (NOT SAM2). Human correction expected. "
                    "SAM2 GPU proposals activate automatically when a GPU is present."}


# ---------------- Mask generation on approve ----------------

def polygons_to_mask(polygons, size):
    im = Image.new("L", size, 0)
    d = ImageDraw.Draw(im)
    for poly in polygons or []:
        if len(poly) >= 3:
            d.polygon([tuple(p) for p in poly], fill=255)
    return im


def generate_and_store(dataset_id: str, ext: str, size, planes: list,
                       occlusions: list, notes: str, view_type: str = None,
                       coordinate_space: str = "exif_applied_display") -> dict:
    """Generate per-plane masks (255/0), merged mask, and spec-compliant meta JSON.
    Masks are generated in the EXIF-applied display coordinate space (same pixels the
    annotator saw and the browser rendered), so image and mask never misalign."""
    w, h = size
    merged = np.zeros((h, w), np.uint8)
    plane_records = []
    parapets = []

    for idx, plane in enumerate(planes, start=1):
        is_parapet = bool(plane.get("is_parapet"))
        suffix = "-parapet" if is_parapet else ""
        plane_id = f"plane-{idx:02d}"
        fname = f"{plane_id}{suffix}.png"
        mask_img = polygons_to_mask(plane.get("polygons", []), (w, h))
        buf = io.BytesIO()
        mask_img.save(buf, format="PNG")
        storage.put_object(config.plane_path(dataset_id, fname), buf.getvalue(), "image/png")
        merged = np.maximum(merged, np.array(mask_img))
        rec = {
            "index": idx, "plane_id": plane_id, "name": plane.get("name", plane_id),
            "file": fname, "is_parapet": is_parapet,
            "generation_method": plane.get("generation_method", "manual_polygon"),
            "human_corrected": bool(plane.get("human_corrected", True)),
            "human_approved": True,
        }
        plane_records.append(rec)
        if is_parapet:
            parapets.append(plane_id)  # spec: "parapets": ["plane-02"]

    merged_buf = io.BytesIO()
    Image.fromarray(merged).save(merged_buf, format="PNG")
    storage.put_object(config.merged_path(dataset_id), merged_buf.getvalue(), "image/png")

    meta = {
        "file": f"{dataset_id}.{ext}",
        "occlusions": occlusions or [],   # spec: [{type, bbox:[x0,y0,x1,y1] normalized, hides:[plane-NN]}]
        "parapets": parapets,             # spec: ["plane-02"]
        "notes": notes or "",
        "view_type": view_type or "uncertain",
        "planes": plane_records,
        "spec_version": "roofline-labeling-spec-v1",
        "coordinate_space": coordinate_space,
        "image_size": {"width": w, "height": h},
    }
    storage.put_object(config.meta_path(dataset_id),
                       json.dumps(meta, indent=2).encode(), "application/json")
    return {"merged": config.merged_path(dataset_id),
            "planes": [config.plane_path(dataset_id, p["file"]) for p in plane_records],
            "meta": meta}
